export const SET_ORGANIZATION_LIST = "SET_ORGANIZATION_LIST";

export const SET_EVENT_LIST = "SET_EVENT_LIST";

// Navigation
export const SET_BACK_LOCATION = "SET_BACK_LOCATION";
export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";
