export const SET_ORGANIZATION_LIST = "SET_ORGANIZATION_LIST";

export const SET_EVENT_LIST = "SET_EVENT_LIST";

export const SET_LAYOUT_BACK_REQUIRED = "SET_LAYOUT_BACK_REQUIRED";
export const SET_LAYOUT_SEARCH_BAR_REQUIRED = "SET_LAYOUT_SEARCH_BAR_REQUIRED";
