export const SET_ORGANIZATION_LIST = "SET_ORGANIZATION_LIST";

export const SET_EVENT_LIST = "SET_EVENT_LIST";

// Navigation
export const SET_BACK_LOCATION = "SET_BACK_LOCATION";
export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";

// Toast
export const SET_TOAST_SUCCESS_MESSAGE = "SET_TOAST_SUCCESS_MESSAGE";
export const SET_TOAST_ERROR_MESSAGE = "SET_TOAST_ERROR_MESSAGE";
export const SET_TOAST_INFO_MESSAGE = "SET_TOAST_INFO_MESSAGE";
export const SET_TOAST_WARNING_MESSAGE = "SET_TOAST_WARNING_MESSAGE";
export const SET_TOAST_ERASE_ALL_MESSAGES = "SET_TOAST_ERASE_ALL_MESSAGES";
export const SET_TOAST_ERASE_MESSAGE = "SET_TOAST_ERASE_MESSAGE";
